# Adding Deleting Columns

In [2]:
import pandas as pd

In [3]:
coffee = pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/master/warmup-data/coffee.csv')
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

#### Lets add a new column 'price'

In [4]:
coffee['price'] = 10        # adds a new column 'price' with a deafult value 10
coffee

          Day Coffee Type  Units Sold  price
0      Monday    Espresso          25     10
1      Monday       Latte          15     10
2     Tuesday    Espresso          30     10
3     Tuesday       Latte          20     10
4   Wednesday    Espresso          35     10
5   Wednesday       Latte          25     10
6    Thursday    Espresso          40     10
7    Thursday       Latte          30     10
8      Friday    Espresso          45     10
9      Friday       Latte          35     10
10   Saturday    Espresso          45     10
11   Saturday       Latte          35     10
12     Sunday    Espresso          45     10
13     Sunday       Latte          35     10

#### To spcifically set values, we use numpy's conditional method

In [5]:
import numpy as np
coffee['price'] = np.where(coffee['Coffee Type'] == 'Espresso', 15, 20)
# syntax is: where(case,if true,else)
coffee

          Day Coffee Type  Units Sold  price
0      Monday    Espresso          25     15
1      Monday       Latte          15     20
2     Tuesday    Espresso          30     15
3     Tuesday       Latte          20     20
4   Wednesday    Espresso          35     15
5   Wednesday       Latte          25     20
6    Thursday    Espresso          40     15
7    Thursday       Latte          30     20
8      Friday    Espresso          45     15
9      Friday       Latte          35     20
10   Saturday    Espresso          45     15
11   Saturday       Latte          35     20
12     Sunday    Espresso          45     15
13     Sunday       Latte          35     20

##### To drop specific index, we use

In [6]:
coffee.drop(0)

          Day Coffee Type  Units Sold  price
1      Monday       Latte          15     20
2     Tuesday    Espresso          30     15
3     Tuesday       Latte          20     20
4   Wednesday    Espresso          35     15
5   Wednesday       Latte          25     20
6    Thursday    Espresso          40     15
7    Thursday       Latte          30     20
8      Friday    Espresso          45     15
9      Friday       Latte          35     20
10   Saturday    Espresso          45     15
11   Saturday       Latte          35     20
12     Sunday    Espresso          45     15
13     Sunday       Latte          35     20

#### For dropping a columns, we use

In [7]:
coffee.drop(columns=['price'])

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

##### However this does not actually modifies it

##### To actually modify the data

In [8]:
#coffee.drop(columns=['price'],inplace=True)
#coffee

#### To add a new column with some math calculation

In [9]:
coffee['revenue'] = coffee['Units Sold']*coffee['price']
coffee

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso          25     15      375
1      Monday       Latte          15     20      300
2     Tuesday    Espresso          30     15      450
3     Tuesday       Latte          20     20      400
4   Wednesday    Espresso          35     15      525
5   Wednesday       Latte          25     20      500
6    Thursday    Espresso          40     15      600
7    Thursday       Latte          30     20      600
8      Friday    Espresso          45     15      675
9      Friday       Latte          35     20      700
10   Saturday    Espresso          45     15      675
11   Saturday       Latte          35     20      700
12     Sunday    Espresso          45     15      675
13     Sunday       Latte          35     20      700

### To rename a column

In [10]:
coffee.rename(columns={'price':'unit_price'},inplace=True)
# old value : new value
coffee

          Day Coffee Type  Units Sold  unit_price  revenue
0      Monday    Espresso          25          15      375
1      Monday       Latte          15          20      300
2     Tuesday    Espresso          30          15      450
3     Tuesday       Latte          20          20      400
4   Wednesday    Espresso          35          15      525
5   Wednesday       Latte          25          20      500
6    Thursday    Espresso          40          15      600
7    Thursday       Latte          30          20      600
8      Friday    Espresso          45          15      675
9      Friday       Latte          35          20      700
10   Saturday    Espresso          45          15      675
11   Saturday       Latte          35          20      700
12     Sunday    Espresso          45          15      675
13     Sunday       Latte          35          20      700

In [11]:
bios = pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/master/data/bios.csv')

In [12]:
bios_new = bios.copy()      #copies to new variable
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

#### To access a part of the entire name from the full name

In [13]:
bios_new['first name'] = bios_new['name'].str.split(' ').str.get(0)
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first name
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert
...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill

#### To work with dates, convert them to date-time format

In [15]:
bios_new['born_date'] = pd.to_datetime(bios_new['born_date'])
bios_new['died_date'] = pd.to_datetime(bios_new['died_date'])
bios_new
# thus type of data is changed to datetime

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first name
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaT,Arnaud
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert
...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaT,Polina
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaT,Valeriya
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaT,Yuliya
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill

In [16]:
bios_new.dtypes

athlete_id               int64
name                    object
born_date       datetime64[ns]
born_city               object
born_region             object
born_country            object
NOC                     object
height_cm              float64
weight_kg              float64
died_date       datetime64[ns]
first name              object
dtype: object

#### After converting to datatime type, we can use the datetime functions using .dt similar to .str

In [17]:
bios_new['born_year'] = bios_new['born_date'].dt.year   #adding a new column named born year
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first name,born_year
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886.0
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaT,Arnaud,1969.0
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898.0
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895.0
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878.0
...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaT,Polina,2002.0
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaT,Valeriya,1999.0
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaT,Yuliya,1998.0
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André,1899.0
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill,1913.0

In [20]:
bios_new[['name','born_year']].head()

                    name  born_year
0  Jean-François Blanchy     1886.0
1         Arnaud Boetsch     1969.0
2           Jean Borotra     1898.0
3        Jacques Brugnon     1895.0
4           Albert Canet     1878.0

##### We can even pass the format of the date explicitly by using the following

In [ ]:
#bios_new['born_date'] = pd.to_datetime(bios_new['born_date'], format = '%Y-%m-%d', errors = 'coerce')
#errors arg is passed for handling the error

### To save the file

In [21]:
bios_new.to_csv('bios_new.csv', index = "False")    #index arg is imp for so it doesn't save the values from the ouput

In [26]:
bios_new['height_category'] = bios_new['height_cm'].apply(lambda x: 'short' if x < 160 else ('Average' if x<180 else 'tall'))
bios_new.head(10)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first name,born_year,height_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886.0,tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaT,Arnaud,1969.0,tall
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898.0,tall
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895.0,Average
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878.0,tall
5,6,Nicolas Chatelain,1970-01-13,Amiens,Somme,FRA,France,181.0,70.0,NaT,Nicolas,1970.0,tall
6,7,Patrick Chila,1969-11-27,Ris-Orangis,Essonne,FRA,France,180.0,73.0,NaT,Patrick,1969.0,tall
7,8,Henri Cochet,1901-12-14,Villeurbanne,Rhône,FRA,France,NaN,NaN,1987-04-02,Henri,1901.0,tall
8,9,Marcel Cousin,1896-08-04,Nîmes,Gard,FRA,France,NaN,NaN,1986-08-01,Marcel,1896.0,tall
9,10,Guy de la Chapelle,1868-07-16,Farges-Allichamps,Cher,FRA,France,NaN,NaN,1923-08-27,Guy,1868.0,tall

### Writing custom functions

In [27]:
def athlete_category(row):
    if row['height_cm'] < 175 and row['weight_kg'] < 70:
        return 'Light Weight'
    elif row['height_cm'] < 190 and row['weight_kg'] <= 90:
        return 'Middle Weight'
    else:
        return 'Heavy weight'

In [28]:
bios_new['athlete_category'] = bios_new.apply(athlete_category, axis = 1)       #axis 1 for rows, 0 for columns
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first name,born_year,height_category,athlete_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886.0,tall,Heavy weight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaT,Arnaud,1969.0,tall,Middle Weight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898.0,tall,Middle Weight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895.0,Average,Light Weight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878.0,tall,Heavy weight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaT,Polina,2002.0,Average,Light Weight
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaT,Valeriya,1999.0,Average,Light Weight
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaT,Yuliya,1998.0,Average,Light Weight
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André,1899.0,Average,Heavy weight
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill,1913.0,tall,Heavy weight